package com.hermes.agent.ui.bloub

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.abs
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin

/**
 * Fidelity tests for the Bloub port.
 *
 * The point of this file is not that the engine "works" — it is that it produces
 * the SAME numbers as the TypeScript it was ported from. The reference values in
 * the first few tests were generated by running the original algorithms
 * (`createRng`, `eyePoses`, `loopNoise` from `src/bot/math.ts` and
 * `src/bot/face.ts`) under Node, so a transcription slip in the bit twiddling or
 * in the order of the three rotations fails here rather than showing up as a
 * face that is subtly wrong.
 *
 * The rest assert the claims the reference README makes about the avatar, which
 * are the things a well-meaning "cleanup" would break.
 */
class BloubEngineTest {

    private val eps = 1e-9

    // ── transcription ───────────────────────────────────────────────────────

    @Test
    fun `mulberry32 matches the reference implementation`() {
        val a = createRng(0x5eed)
        val expectedA = doubleArrayOf(
            0.710032036994, 0.286336648511, 0.951902626548, 0.101759762270, 0.378413929138,
        )
        for (v in expectedA) assertEquals(v, a(), 1e-12)

        val b = createRng(0xa11ce)
        val expectedB = doubleArrayOf(
            0.743155926233, 0.562341528479, 0.223274309188, 0.758930709446, 0.560476952931,
        )
        for (v in expectedB) assertEquals(v, b(), 1e-12)
    }

    @Test
    fun `eye poses match the reference sphere model`() {
        val poses = eyePoses(REST_GAZE, 100.0, EYE_SPLIT)

        // inner eye
        assertEquals(18.899315016, poses[0].x, 1e-8)
        assertEquals(-40.902907542, poses[0].y, 1e-8)
        assertEquals(0.887466799, poses[0].a, 1e-8)
        assertEquals(-0.318005111, poses[0].b, 1e-8)
        assertEquals(0.420338280, poses[0].c, 1e-8)
        assertEquals(0.855317464, poses[0].d, 1e-8)
        assertEquals(0.892735574, poses[0].depth, 1e-8)

        // outer eye
        assertEquals(61.815109931, poses[1].x, 1e-8)
        assertEquals(-51.430413363, poses[1].y, 1e-8)
        assertEquals(0.664232601, poses[1].a, 1e-8)
        assertEquals(-0.062636200, poses[1].b, 1e-8)
        assertEquals(0.594458137, poses[1].depth, 1e-8)
    }

    @Test
    fun `loop noise matches the reference`() {
        assertEquals(0.365510749072, loopNoise(1.234, 11.3, 0.4), 1e-12)
        assertEquals(0.132008693676, loopNoise(7.7, 5.3, 0.3), 1e-12)
    }

    @Test
    fun `the measured profiles keep their sampling and their footprints`() {
        for (name in listOf("egg", "hexagon", "triangle")) {
            assertEquals(64, BloubProfiles.byName(name).size)
        }
        // The footprints the extraction recorded on the reference frames, in
        // ball-radius units. The tolerance is what resampling to 64 angles costs:
        // the profile is a polygon through the samples, so its bounding box sits a
        // few thousandths outside the measured one.
        assertEquals(1.647, footprint(BloubProfiles.EGG).first, 0.01)
        assertEquals(2.000, footprint(BloubProfiles.EGG).second, 0.01)
        assertEquals(1.826, footprint(BloubProfiles.HEXAGON).first, 0.01)
        assertEquals(2.011, footprint(BloubProfiles.HEXAGON).second, 0.01)
        assertEquals(1.995, footprint(BloubProfiles.TRIANGLE).first, 0.01)
        assertEquals(1.884, footprint(BloubProfiles.TRIANGLE).second, 0.01)
    }

    // ── the claims the avatar depends on ────────────────────────────────────

    @Test
    fun `the resting body is a true circle, not a squircle`() {
        // The README's measurement: radial deviation under 0.7 %.
        val frame = BotEngine(100.0, StateId.IDLE).sample(1.0)
        val radii = frame.body!!.cubics.map { kotlin.math.hypot(it.x, it.y) }
        val mean = radii.average()
        val deviation = radii.maxOf { abs(it - mean) } / mean
        assertTrue("radial deviation $deviation exceeds 0.7 %", deviation < 0.007)
    }

    @Test
    fun `the eyes lean backslash, not slash`() {
        // The single most counter-intuitive measurement in the reference: the
        // capsules lean "\\", about 26 degrees off vertical. Straightening them —
        // or mirroring them to "//" — is the change that makes the face generic.
        val frame = BotEngine(100.0, StateId.IDLE).sample(1.0)
        for (eye in frame.eyes) {
            // the capsule's long axis is its local y, so the second matrix column
            val angleOffVertical = Math.toDegrees(atan2(eye.c, eye.d))
            assertTrue(
                "eye leans $angleOffVertical degrees, expected about +26",
                angleOffVertical in 20.0..32.0,
            )
        }
    }

    @Test
    fun `the body never overshoots during a transition`() {
        // Measured on the video: exponential ease-outs, no spring. Only the
        // notification pip and the eyes opening overshoot, and they say so in their
        // own state. idle -> burst is the clean case to measure: both bodies are
        // centred circles, so the radius alone tells the whole story as it collapses
        // from 1.0 towards 0.166.
        val engine = BotEngine(100.0, StateId.IDLE)
        engine.setState(StateId.BURST, 0.0)
        val morph = STATE_BY_ID.getValue(StateId.BURST).morph
        // the resting breath moves the height by half a percent
        val ceiling = 100.0 * 1.006
        var t = 0.0
        while (t <= morph) {
            for (c in engine.sample(t).body!!.cubics) {
                val r = kotlin.math.hypot(c.x, c.y)
                assertTrue("radius $r overshot the starting radius at t=$t", r <= ceiling)
                assertTrue("radius $r undershot the target at t=$t", r >= 0.166 * 100 * 0.99)
            }
            t += morph / 20
        }
    }

    @Test
    fun `re-reading a date before a state change does not extrapolate`() {
        // The ratio fed to the ease-out is clamped. Without that, a negative ratio
        // is extrapolated and the silhouette flies off — measured at thirty times
        // too far in the reference.
        val engine = BotEngine(100.0, StateId.IDLE)
        engine.setState(StateId.BURST, 1.0)
        for (c in engine.sample(0.5).body!!.cubics) {
            val r = kotlin.math.hypot(c.x, c.y)
            assertTrue("radius $r extrapolated backwards", r in 1.0..(100.0 * 1.01))
        }
    }

    @Test
    fun `sample is a pure function of time`() {
        val engine = BotEngine(100.0, StateId.IDLE)
        engine.setState(StateId.WIDE, 0.3)

        val a = engine.sample(0.42)
        // walk well past the fade, then come back to the same date
        engine.sample(5.0)
        val b = engine.sample(0.42)

        assertEquals(a.body!!.cubics.size, b.body!!.cubics.size)
        for (i in a.body!!.cubics.indices) {
            assertEquals(a.body!!.cubics[i].x, b.body!!.cubics[i].x, eps)
            assertEquals(a.body!!.cubics[i].y, b.body!!.cubics[i].y, eps)
        }
        assertEquals(a.eyes.size, b.eyes.size)
        for (i in a.eyes.indices) {
            assertEquals(a.eyes[i].e, b.eyes[i].e, eps)
            assertEquals(a.eyes[i].f, b.eyes[i].f, eps)
            assertEquals(a.eyes[i].alpha, b.eyes[i].alpha, eps)
        }
    }

    @Test
    fun `the orbit rings stay inside the viewBox`() {
        // Nothing bounds them at runtime: it is the hand-tuned RINGS and SWOOSH
        // tables that keep them under the half-viewBox, and this is what locks it.
        val engine = BotEngine(BloubFrame.RADIUS, StateId.ORBIT)
        var t = 0.0
        while (t <= 3.4) {
            val frame = engine.sample(t)
            for (arc in frame.arcs) {
                for (run in arc.front + arc.back) {
                    var i = 0
                    while (i < run.size) {
                        val margin = arc.width / 2
                        assertTrue(
                            "arc reached ${run[i]} at t=$t",
                            abs(run[i]) + margin <= BloubFrame.HALF_VIEWBOX,
                        )
                        assertTrue(
                            "arc reached ${run[i + 1]} at t=$t",
                            abs(run[i + 1]) + margin <= BloubFrame.HALF_VIEWBOX,
                        )
                        i += 2
                    }
                }
            }
            t += 0.05
        }
    }

    // ── the arrival ─────────────────────────────────────────────────────────

    @Test
    fun `the arrival script never imposes a direction and ends at rest`() {
        // Two rules the reference paid for. A gaze script must END at `mix: 0`,
        // where the state's own pose commands alone — otherwise there is something
        // left to release, and the release shows up as one last slide of the eyes
        // exactly when everything should be settling.
        //
        // And `mix` stays at zero THROUGHOUT: the turn imposes no direction, it
        // only unwinds `spin`, which is what carries the eyes behind the ball and
        // brings them back precisely where the chosen expression puts them.
        var t = 0.0
        while (t <= BloubLook.TOUR_TIME) {
            assertEquals("mix moved at t=$t", 0.0, BloubLook.tourLook(t).mix, 0.0)
            t += BloubLook.TOUR_TIME / 20
        }

        val start = BloubLook.tourLook(0.0)
        val end = BloubLook.tourLook(BloubLook.TOUR_TIME)
        // a whole turn to travel, and -360 degrees is the same angle as 0, so it
        // lands right by construction rather than wherever a curve happened to end
        assertEquals(BloubLook.SPIN, start.spin, 1e-9)
        assertEquals(0.0, end.spin, 1e-9)
        assertEquals(0.0, end.mix, 0.0)
        // the resting drift is never suppressed: the ball has to stay alive
        assertEquals(1.0, end.wander, 0.0)
    }

    @Test
    fun `the arrival turn is ease-in-out, not the exponential ease-out`() {
        // Under the ease-out used everywhere else, two thirds of the turn were
        // swallowed in the first 0.3 s — a jolt, not a rotation. Halfway through
        // the turn an ease-in-out is halfway round; an ease-out is long past it.
        val half = BloubLook.tourLook(BloubLook.TOUR_TIME / 2).spin / BloubLook.SPIN
        assertEquals("the turn is not symmetric at its midpoint", 0.5, half, 1e-9)
    }

    // ── the eye-fit table, which exists for exactly one bug ─────────────────

    @Test
    fun `the circle needs no eye correction`() {
        val off = BloubEyeFit.decalageDesYeux(ShapeId.CERCLE, StateId.IDLE, ExpressionId.NEUTRE)
        assertEquals(0.0, off.x, 0.0)
        assertEquals(0.0, off.y, 0.0)
    }

    @Test
    fun `the pairs that used to overflow all get a correction`() {
        // Exactly the five state x shape pairs the reference measured as pushing an
        // eye out of the silhouette before the table existed: `wide`+`capsule` by
        // 14.5 units on a ball of radius 100, `wide`+`triangle` by 11.9,
        // `idle`+`capsule` and `swirl`+`capsule` by 5.3, `notify`+`goutte` by 3.3.
        val overflowed = listOf(
            Triple(ShapeId.CAPSULE, StateId.WIDE, null),
            Triple(ShapeId.TRIANGLE, StateId.WIDE, null),
            Triple(ShapeId.CAPSULE, StateId.IDLE, ExpressionId.NEUTRE),
            Triple(ShapeId.CAPSULE, StateId.SWIRL, ExpressionId.NEUTRE),
            Triple(ShapeId.GOUTTE, StateId.NOTIFY, null),
        )
        for ((shape, state, expression) in overflowed) {
            val off = BloubEyeFit.decalageDesYeux(shape, state, expression)
            assertNotEquals(
                "$shape on $state produced no correction at all",
                0.0,
                abs(off.x) + abs(off.y),
                1e-6,
            )
        }
    }

    @Test
    fun `a state that draws its own body is never corrected`() {
        // The customiser's shape does not reach `thinking` (three dots) or `sleep`
        // (a bouncing dot), so there is nothing there to correct.
        for (state in listOf(StateId.THINKING, StateId.SLEEP, StateId.EXCLAIM, StateId.BURST)) {
            val off = BloubEyeFit.decalageDesYeux(ShapeId.TRIANGLE, state, ExpressionId.NEUTRE)
            assertEquals(0.0, off.x, 0.0)
            assertEquals(0.0, off.y, 0.0)
        }
    }

    @Test
    fun `no shape lets an eye out of the silhouette`() {
        // The regression the whole eye-fit table was written for: an eye that leaves
        // the silhouette is cropped by the mask and reads as a notch cut out of the
        // body.
        //
        // This sweeps TIME and not just the combination, which is the reference's
        // own hard-won lesson: the gaze drift moves an eye a dozen units, so a
        // single frame proves nothing. Measuring only at POSES[state] is exactly how
        // `capsule` + `effraye` went unnoticed while it stuck out by 4.4 units a
        // second later.
        val instants = 60
        val step = 1.0 / 20
        val faults = ArrayList<String>()

        for (def in STATES.filter { it.baseBody }) {
            for (shape in ShapeId.entries) {
                for (expression in listOf<ExpressionId?>(null) + ExpressionId.entries) {
                    val engine = BotEngine(100.0, def.id, shape, expression?.let { EXPRESSION_BY_ID[it] })
                    var worst = 0.0
                    for (i in 0 until instants) {
                        val frame = engine.sample(i * step)
                        val polygon = frame.body!!.cubics.map { Pt(it.x, it.y) }
                        for (eye in frame.eyes) {
                            for (p in capsuleOutline(eye)) {
                                if (inside(polygon, p)) continue
                                worst = max(worst, polygon.minOf { kotlin.math.hypot(it.x - p.x, it.y - p.y) })
                            }
                        }
                    }
                    if (worst > 0.05) {
                        faults.add("${def.id.id}/${shape.id}/${expression?.id ?: "pose"} %.1f".format(worst))
                    }
                }
            }
        }

        assertTrue("eyes left the body: $faults", faults.isEmpty())
    }

    // ── helpers ─────────────────────────────────────────────────────────────

    /** Width and height of a profile's bounding box, in ball-radius units. */
    private fun footprint(radii: DoubleArray): Pair<Double, Double> {
        var minX = Double.MAX_VALUE
        var maxX = -Double.MAX_VALUE
        var minY = Double.MAX_VALUE
        var maxY = -Double.MAX_VALUE
        for (i in radii.indices) {
            val x = radii[i] * BloubShape.COS[i]
            val y = radii[i] * BloubShape.SIN[i]
            minX = min(minX, x); maxX = max(maxX, x)
            minY = min(minY, y); maxY = max(maxY, y)
        }
        return (maxX - minX) to (maxY - minY)
    }

    /** The body's vertical centre, so a bouncing state can be measured about it. */
    private fun offsetY(frame: BotFrame): Double = frame.body!!.cubics.map { it.y }.average()

    /**
     * The stadium's outline in screen space: both cap circles plus the flanks
     * between them, so a capsule poking out sideways is caught as well as one
     * poking out end-on.
     */
    private fun capsuleOutline(eye: RenderedEye): List<Pt> {
        val cap = eye.capsule
        val long = cap.halfH > cap.halfW
        val half = (if (long) cap.halfH else cap.halfW) - cap.r
        val out = ArrayList<Pt>(64)

        fun local(x: Double, y: Double) = Pt(
            eye.a * x + eye.c * y + eye.e,
            eye.b * x + eye.d * y + eye.f,
        )

        for (sign in doubleArrayOf(-1.0, 1.0)) {
            val cx = if (long) 0.0 else sign * half
            val cy = if (long) sign * half else 0.0
            for (k in 0 until 24) {
                val a = (k / 24.0) * TAU
                out.add(local(cx + cos(a) * cap.r, cy + sin(a) * cap.r))
            }
        }
        for (k in 1..5) {
            val u = -half + 2 * half * k / 6.0
            if (long) {
                out.add(local(cap.r, u))
                out.add(local(-cap.r, u))
            } else {
                out.add(local(u, cap.r))
                out.add(local(u, -cap.r))
            }
        }
        return out
    }

    /** Ray casting. The polygon is the profile's 64 samples, so slightly inside the drawn curve. */
    private fun inside(poly: List<Pt>, p: Pt): Boolean {
        var hit = false
        var j = poly.size - 1
        for (i in poly.indices) {
            val a = poly[i]
            val b = poly[j]
            if ((a.y > p.y) != (b.y > p.y) &&
                p.x < (b.x - a.x) * (p.y - a.y) / (b.y - a.y) + a.x
            ) {
                hit = !hit
            }
            j = i
        }
        return hit
    }
}
