package com.hermes.agent.domain.model
import com.hermes.agent.domain.llm.*

/**
 * A single chat message inside a conversation.
 *
 * This is the domain-layer representation. The persistence layer maps it to
 * [com.hermes.agent.data.local.entity.MessageEntity]; the LLM layer maps it
 * to [com.hermes.agent.data.llm.LlmMessage].
 *
 * @property id Stable unique identifier (UUID).
 * @property conversationId Owning conversation.
 * @property role Who produced the message — user, assistant, system, or tool.
 * @property content Rendered text content.
 * @property agentRole Which specialized agent produced this message (null for
 *   USER / SYSTEM / TOOL messages). Always non-null for ASSISTANT messages
 *   produced by Hermes.
 * @property timestamp Wall-clock millis when the message was created.
 * @property tokens Approximate token count (used for context-window budgeting).
 * @property isOnDevice Whether the message was generated by the on-device
 *   provider (true) or a cloud provider (false). Surfaced in the UI so the
 *   user can tell which responses stayed on-device, per Section 5.1 of the
 *   plan.
 */
data class Message(
    val id: String,
    val conversationId: String,
    val role: MessageRole,
    val content: String,
    val agentRole: AgentRole? = null,
    val timestamp: Long,
    val tokens: Int = 0,
    val isOnDevice: Boolean = true,
    val evidenceState: EvidenceState? = null,
)
